version: '3.8'
services:
  web:
    build: .
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - MODEL_PATH=/app/models/model.pkl
    command: python src/train.py  # <== временно, чтобы обучить модель
